---
title: "Explanatory plot"
output: html_document
---

How should parasites divide their growth and development among the multiple hosts of a complex life cycle? Here we look at parasite life history strategies in two-host life cycles.

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
options(stringsAsFactors = FALSE)
theme_set(new = theme_bw())
```

# Optimal strategies

```{r}
size <- c(0, 2, 4)
age <- c(0, 2, 4)
dp <- data.frame(size, age, stage = c("propagule", "int", "def"))
```
```{r}
pal <- RColorBrewer::brewer.pal(n = 8, name = "Paired")
```

```{r}
f1a <- ggplot(dp, aes(age, size)) +
  geom_line() +
  geom_point(data = dp%>%filter(size!=0),
             size = 4, 
             shape = 1) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        # axis.text = element_blank(),
        # axis.ticks = element_blank()
        ) +
  scale_x_continuous(breaks = c(0, dp$age[2], dp$age[3]), 
                     labels = c("0", "Age at\ninfectivity", "Age at\nmaturity")) +
  scale_y_continuous(breaks = c(0, dp$size[2], dp$size[3]), 
                     labels = c("Propagule\nsize", "Larval size\nat infectivity", "Adult size\nat maturity")) +
  labs(x = "Age", y = "Body size") +
  # dotted lines from axes
  annotate("segment",
           x = dp$age[2], xend = dp$age[2],
           y = 0, yend = dp$size[2],
           linetype = "dotted") +
  annotate("segment",
           x = dp$age[3], xend = dp$age[3],
           y = 0, yend = dp$size[3],
           linetype = "dotted") +
  annotate("segment",
           y = dp$size[2], yend = dp$size[2],
           x = 0, xend = dp$age[2],
           linetype = "dotted") +
  annotate("segment",
           y = dp$size[3], yend = dp$size[3],
           x = 0, xend = dp$age[3],
           linetype = "dotted") +
  # relative growth lines
  annotate("segment",
           y = 0, yend = dp$size[2],
           x = 0, xend = 0,
           arrow = arrow(ends = "both", angle = 20, type = "open"),
           color = pal[1]
           ) +
  annotate("segment",
           y = dp$size[2], yend = dp$size[3],
           x = 0, xend = 0,
           arrow = arrow(ends = "both", angle = 20, type = "open"),
           color = pal[2]) +
  annotate("label",
           label = "RG, IH",
           x = 0,
           y = dp$size[2]/2,
           hjust = 0.2,
           color = pal[1]) + 
  annotate("label",
           label = "RG, DH",
           x = 0,
           y = (dp$size[2] + dp$size[3])/2, 
           hjust = 0.2,
           color = pal[2]) +
  # devo time lines
  annotate("segment",
           y = 0, yend = 0,
           x = 0, xend = dp$age[2],
           arrow = arrow(ends = "both", angle = 20, type = "open"),
           color = pal[3]
           ) +
  annotate("segment",
           y = 0, yend = 0,
           x = dp$age[2], xend = dp$age[3],
           arrow = arrow(ends = "both", angle = 20, type = "open"),
           color = pal[4]) +
  annotate("label",
           label = "DT, IH",
           y = 0,
           x = dp$age[2]/2, 
           vjust = 0.2,
           color = pal[3]) + 
  annotate("label",
           label = "DT, DH",
           y = 0,
           x = (dp$age[2] + dp$age[3])/2, 
           vjust = 0.2,
           color = pal[4])
f1a
```

## Better DH
```{r}
pal2 <- RColorBrewer::brewer.pal(6, name = "Dark2")
pal2 <- pal2[3:6]
```

```{r}
# better def host - more growth
size <- c(0, 1.75, 4.5)-0.1
age <- c(0, 1.75, 4.5)
dp2 <- data.frame(size, age, stage = c("propagule", "int", "def"), better_dh = "yes", mg = "c")

# better def host - faster growth
size <- c(0, 1.4, 5)
age <- c(0, 1.4, 3.5)
dp3 <- data.frame(size, age, stage = c("propagule", "int", "def"), better_dh = "yes", mg = "b")

dp_dh <- bind_rows(dp2, dp3, dp%>%mutate(better_dh = "no", mg="a"))
```


```{r}
f1b1 <- ggplot(dp_dh, aes(age, size)) +
  geom_line(aes(group = mg, linetype = better_dh)) +
  geom_point(data = dp_dh%>%filter(size!=0, !size < 0),
             aes(color = better_dh, shape = mg),
             size = 4) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()
        ) +
  scale_color_manual(values = c("black", pal2[1])) +
  scale_shape_manual(values = c(1, 16, 18)) +
  labs(x = "Age", y = "Body size", title = ) +
  # annotate("segment",
  #          y = filter(dp_dh, stage == "int", better_dh == "no")$size, 
  #          yend = filter(dp_dh, stage == "int", better_dh == "yes")$size,
  #          x = filter(dp_dh, stage == "int", better_dh == "no")$age, 
  #          xend = filter(dp_dh, stage == "int", better_dh == "yes")$age,
  #          arrow = arrow(ends = "last", angle = 20, type = "open")
  #          ) +
  # annotate("segment",
  #          y = filter(dp_dh, stage == "def", better_dh == "no")$size,
  #          yend = filter(dp_dh, stage == "def", better_dh == "yes")$size,
  #          x = filter(dp_dh, stage == "def", better_dh == "no")$age,
  #          xend = filter(dp_dh, stage == "def", better_dh == "yes")$age,
  #          arrow = arrow(ends = "last", angle = 20, type = "open")
  #          ) +
  annotate("segment", # for low mort/fast grow
           y = 3.75,
           yend = 4.9,
           x = 2.3,
           xend = 3.4,
           arrow = arrow(ends = "last", angle = 20, type = "open", length = unit(0.1, "inches") ),
           ) +
  annotate("segment", # for low mort
           y = 2.75,
           yend = 4.3,
           x = 4.3,
           xend = 4.5,
           arrow = arrow(ends = "last", angle = 20, type = "open", length = unit(0.1, "inches") ),
           ) +
  annotate("label",
           label = "Better DH",
           y = 0, 
           x = max(dp_dh$age), 
           color = pal2[1],
           hjust = 1, vjust = 0
           ) +
  annotate("text",
           label = "Faster growth\nLower mortality",
           y = 3.8, 
           x = 2.25, 
           color = pal2[1],
           hjust = 1, 
           # vjust = 0,
           size = 3
           ) +
  annotate("text",
           label = "Lower\nmortality",
           y = 2.75, 
           x = 4.5, 
           color = pal2[1],
           hjust = 1, vjust = 1,
           size = 3
           ) +
  guides(shape = F, linetype = F, color = F)
f1b1
```


## Better IH

```{r}
# better int host - just more growth
size <- c(0-.1, 2.5, 4)
age <- c(0, 2.6, 4.1)
dp2 <- data.frame(size, age, stage = c("propagule", "int", "def"), better_dh = "yes", mg = "c")

# better int host - faster growth
size <- c(0, 2.5, 4)
age <- c(0, 1.5, 3)
dp3 <- data.frame(size, age, stage = c("propagule", "int", "def"), better_dh = "yes", mg = "b")


dp_dh <- bind_rows(dp2, dp3, dp%>%mutate(better_dh = "no", mg="a"))
```

```{r}
f1b2 <- ggplot(dp_dh, aes(age, size)) +
  geom_line(aes(group = mg, linetype = better_dh)) +
  geom_point(data = dp_dh%>%filter(size!=0, !size < 0),
             aes(color = better_dh, shape = mg),
             size = 4) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()
        ) +
  scale_color_manual(values = c("black", pal2[2])) +
  scale_shape_manual(values = c(1, 16, 18)) +
  labs(x = "Age", y = "Body size", title = ) +
  # annotate("segment",
  #          y = filter(dp_dh, stage == "int", better_dh == "no")$size, 
  #          yend = filter(dp_dh, stage == "int", better_dh == "yes")$size,
  #          x = filter(dp_dh, stage == "int", better_dh == "no")$age, 
  #          xend = filter(dp_dh, stage == "int", better_dh == "yes")$age,
  #          arrow = arrow(ends = "last", angle = 20, type = "open"),
  #          # color = pal[5]
  #          ) +
  # annotate("segment",
  #          y = filter(dp_dh, stage == "def", better_dh == "no")$size, 
  #          yend = filter(dp_dh, stage == "def", better_dh == "yes")$size,
  #          x = filter(dp_dh, stage == "def", better_dh == "no")$age, 
  #          xend = filter(dp_dh, stage == "def", better_dh == "yes")$age,
  #          arrow = arrow(ends = "last", angle = 20, type = "open"),
  #          # color = pal[6]
  #          ) +
  annotate("segment",
           y = 3.2,
           yend = 2.6,
           x = 1.5,
           xend = 1.5,
           arrow = arrow(ends = "last", angle = 20, type = "open", length = unit(0.1, "inches") ),
           ) +
  annotate("segment",
           y = 1.7,
           yend = 2.4,
           x = 2.6,
           xend = 2.6,
           arrow = arrow(ends = "last", angle = 20, type = "open", length = unit(0.1, "inches") ),
           ) +
  annotate("label",
           label = "Better IH",
           x = max(dp_dh$age), 
           y = 0,
           color = pal2[2],
           hjust = 1, vjust = 0
           ) +
  annotate("text",
           label = "Faster growth\nLower mortality",
           y = 3.55, 
           x = 2, 
           color = pal2[2],
           hjust = 1, 
           # vjust = 0,
           size = 3
           ) +
  annotate("text",
           label = "Lower mortality",
           y = 1.7, 
           x = 2.1, 
           color = pal2[2],
           hjust = 0, vjust = 1,
           size = 3
           ) +
  guides(shape = F, linetype = F, color = F)
f1b2
```
# Constraints

## Decoupled

```{r}
# better perf in int host
size <- c(0, 2.5, 4)
age <- c(0, 1.5, 3)
dp2 <- data.frame(size, age, stage = c("propagule", "int", "def"), better_dh = "yes")


dp_dh <- bind_rows(dp2, dp%>%mutate(better_dh = "no"))
```

```{r}
f1b3 <- ggplot(dp_dh, aes(age, size)) +
  geom_line(aes(group = better_dh, linetype = better_dh)) +
  geom_point(data = dp_dh%>%filter(size!=0),
             aes(color = better_dh, shape = better_dh),
             size = 4) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()
        ) +
  scale_color_manual(values = c("black", pal2[3])) +
  scale_shape_manual(values = c(1, 16)) +
  labs(x = "Age", y = "Body size", title = ) +
  annotate("segment",
           y = filter(dp_dh, stage == "int", better_dh == "no")$size, 
           yend = filter(dp_dh, stage == "int", better_dh == "yes")$size,
           x = filter(dp_dh, stage == "int", better_dh == "no")$age, 
           xend = filter(dp_dh, stage == "int", better_dh == "yes")$age,
           arrow = arrow(ends = "last", angle = 20, type = "open"),
           # color = pal[5]
           ) +
  annotate("segment",
           y = filter(dp_dh, stage == "def", better_dh == "no")$size, 
           yend = filter(dp_dh, stage == "def", better_dh == "yes")$size,
           x = filter(dp_dh, stage == "def", better_dh == "no")$age, 
           xend = filter(dp_dh, stage == "def", better_dh == "yes")$age,
           arrow = arrow(ends = "last", angle = 20, type = "open"),
           # color = pal[6]
           ) +
  annotate("label",
           label = "Same hosts\nDecoupling",
           y = max(dp_dh$size),
           x = min(dp_dh$age),
           color = pal2[3],
           hjust = 0, vjust = 1
           ) +
  guides(shape = F, linetype = F, color = F)
f1b3
```

## Coupled

```{r}
f1b4 <- ggplot(dp_dh, aes(age, size)) +
  geom_line(aes(group = better_dh, linetype = better_dh)) +
  geom_point(data = dp_dh%>%filter(size!=0),
             aes(color = better_dh, shape = better_dh),
             size = 4) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()
        ) +
  scale_color_manual(values = c("black", "black")) +
  scale_shape_manual(values = c(1, 16)) +
  labs(x = "Age", y = "Body size", title = ) +
  guides(shape = F, linetype = F, color = F)
```


```{r}
pal <- RColorBrewer::brewer.pal(n=8,"Set2")
size <- c(2.5, 2.5, 4,4)
age <- c(1.5, 4.5, 4.5, 3)
dpx <- data.frame(size, age)

size <- c(4, 4, 2.5+1*3)
age <- c(3, 4.5, 4.5)
dpx2 <- data.frame(size, age)

size <- c(2.5, 4, 4)
age <- c(1.5, 1.5, 3)
dpx3 <- data.frame(size, age)

size <- c(4, 5.5, 5.5, 4)
age <- c(1.5, 1.5, 4.5, 3)
dpx4 <- data.frame(size, age)
```


```{r}
f1b4 <- f1b4 + 
  geom_polygon(data = dpx, fill = pal[1], alpha = 0.5) +
  # geom_polygon(data = dpx2, fill = pal[1], alpha = 0.25) +
  # geom_polygon(data = dpx3, fill = pal[2], alpha = 0.25) +
  geom_polygon(data = dpx4, fill = pal[2], alpha = 0.5) +
  annotate("text",
           label = "Tradeoff",
           y = 2.25,
           x = 4.5,
           size = 3.3,
           hjust = 1,
           color = pal[1]
           ) +
  annotate("label",
           label = "Less/slower\nDH growth",
           y = 3.1,
           x = 4.5,
           color = pal[1],
           size = 2.5,
           hjust = 1
           ) +
  # annotate("label",
  #          label = "Slow DH growth",
  #          y = 4.4,
  #          x = 4.5,
  #          color = pal[1],
  #          hjust = 1
  #          ) +
  annotate("text",
           label = "Species trait",
           y = 5.5,
           x = 1.25,
           color = pal[2],
           angle = 90,
           size = 3.3,
           hjust = 1
           ) +
  annotate("label",
           label = "More/faster\nDH growth",
           y = 4.8,
           x = 1.5,
           size = 2.5,
           color = pal[2],
           hjust = 0
           ) +
  # annotate("label",
  #          label = "Fast DH growth",
  #          y = 3.5,
  #          x = 1.5,
  #          color = pal[2],
  #          hjust = 0
  #          ) +
  annotate("label",
           label = "Same hosts",
           y = 0,
           x = 4.5,
           color = "black",
           hjust = 1, vjust = 0
           ) 
f1b4
```

```{r}
library(cowplot)
```

```{r}
# # long fig
# f1ax <- plot_grid(NULL,f1a,NULL,
#                  rel_heights = c(1,2,1),
#                  ncol = 1)
# 
# f1b <- plot_grid(f1b1,f1b2,f1b4, 
#                  labels = c("(b)", "(c)", "(d)"),
#                  ncol = 1)
# 
# f1 <- plot_grid(f1ax, f1b, 
#                 rel_widths = c(1.5, 1),
#                 nrow = 1)
```
```{r}
# ggsave(f1, filename = "../figs/fig1x.png", width = 6, height = 6)
```


```{r}
# wide fig
f1ax <- plot_grid(NULL, 
                  f1a + theme(axis.title = element_blank()),
                  NULL,
                 rel_widths = c(0.75,4,1),
                 nrow = 1, 
                 labels = c("", "A", ""))

f1b <- plot_grid(f1b2,f1b1,f1b4, 
                 align = "hv",
                 labels = c("B", "C", "D"),
                 nrow = 1)
```

```{r}
f1 <- plot_grid(f1ax, f1b, 
                rel_heights = c(1.1, 1),
                ncol = 1)
```
```{r}
ggsave(f1, filename = "../figs/fig1X.png", width = 160, height = 120, units = "mm")
ggsave(f1, filename = "../figs/fig1X.svg", width = 160, height = 120, units = "mm")
```

```{r}
# ggsave(f1, filename = "../figs/fig1x.png", width = 8, height = 12)
# ggsave(f1, filename = "../figs/fig1.svg", width = 8, height = 12)
```

